# Generated by Django 3.1.3 on 2020-11-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
