# Generated by Django 3.1.3 on 2020-11-04 19:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='form',
            name='items',
        ),
    ]
