# Generated by Django 3.1.3 on 2020-11-04 19:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20201104_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='contacts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='form',
            name='items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None),
        ),
    ]
