# Generated by Django 3.1.3 on 2020-11-05 14:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20201105_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='details',
        ),
        migrations.AddField(
            model_name='form',
            name='contacts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None),
        ),
    ]
