# Generated by Django 3.1.3 on 2020-11-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_form_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
